# Generated by Django 4.1 on 2022-09-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Ticker', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=50)),
                ('cotizacion', models.IntegerField(max_length=50)),
                ('cupon', models.FloatField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Familiar',
        ),
    ]
